import type { Category, Unit } from './units'

function u(
  id: string,
  label: string,
  short: string,
  category: Category,
  toBase: number,
  blurb?: string,
): Unit {
  return { id, label, short, category, toBase, weird: true, blurb }
}

/** 100+ absurd units — approximate real-world averages for trivia, not engineering. */
export const UNHINGED_UNITS: Unit[] = [
  // —— Length (meters) ——
  u('capybara', 'Capybaras', '🦫', 'length', 1.3, 'Average adult, nose to tail.'),
  u('eiffel', 'Eiffel Towers', '🗼', 'length', 330, 'Tip of the antenna.'),
  u('banana', 'Bananas', '🍌', 'length', 0.18, 'Internet-standard banana for scale.'),
  u('blue-whale', 'Blue Whales', '🐋', 'length', 24, 'Largest animal ever.'),
  u('school-bus', 'School Buses', '🚌', 'length', 12),
  u('football-field', 'Football Fields', '🏈', 'length', 91.44, 'Goal line to goal line.'),
  u('empire-state', 'Empire State Buildings', '🏙️', 'length', 443),
  u('hot-dog', 'Hot Dogs', '🌭', 'length', 0.15, 'Bun not included.'),
  u('giraffe', 'Giraffes', '🦒', 'length', 5.5, 'Standing height.'),
  u('great-white-shark', 'Great White Sharks', '🦈', 'length', 4.5),
  u('t-rex', 'T. Rexes', '🦖', 'length', 12),
  u('honey-bee', 'Honey Bees', '🐝', 'length', 0.016),
  u('red-blood-cell', 'Red Blood Cells', '🩸', 'length', 0.000008),
  u('grain-of-rice', 'Grains of Rice', '🍚', 'length', 0.006),
  u('credit-card', 'Credit Cards', '💳', 'length', 0.0856),
  u('iphone', 'iPhones', '📱', 'length', 0.16),
  u('basketball-player', 'Average NBA Players', '🏀', 'length', 2.01),
  u('shaq', 'Shaquille O\'Neals', '🦶', 'length', 2.16),
  u('door', 'Standard Doors', '🚪', 'length', 2.03),
  u('queen-bed', 'Queen Beds', '🛏️', 'length', 2.03),
  u('ping-pong-table', 'Ping Pong Tables', '🏓', 'length', 2.74),
  u('tennis-court', 'Tennis Courts', '🎾', 'length', 23.77),
  u('niagara-falls', 'Niagara Falls', '🌊', 'length', 51, 'Drop height.'),
  u('statue-of-liberty', 'Statues of Liberty', '🗽', 'length', 93, 'Ground to torch.'),
  u('big-ben', 'Big Bens', '🕰️', 'length', 96),
  u('great-pyramid', 'Great Pyramids', '🔺', 'length', 146, 'Original height.'),
  u('burj-khalifa', 'Burj Khalifas', '🏗️', 'length', 828),
  u('mount-everest', 'Mount Everests', '🏔️', 'length', 8848),
  u('golden-gate', 'Golden Gate Bridges', '🌉', 'length', 1280, 'Total length.'),
  u('london-bus', 'London Double-Decker Buses', '🚍', 'length', 11.2),
  u('tesla-model-3', 'Tesla Model 3s', '🚗', 'length', 4.69),
  u('boeing-747', 'Boeing 747s', '✈️', 'length', 76),
  u('airbus-a380', 'Airbus A380s', '🛫', 'length', 73),
  u('olympic-pool-length', 'Olympic Pools (length)', '🏊', 'length', 50),
  u('shipping-container', '20-ft Shipping Containers', '📦', 'length', 6.058),
  u('bowling-lane', 'Bowling Lanes', '🎳', 'length', 18.288),
  u('grand-piano', 'Grand Pianos', '🎹', 'length', 2.7),
  u('toothpick', 'Toothpicks', '🪵', 'length', 0.065),
  u('paperclip', 'Paperclips', '📎', 'length', 0.033),
  u('aa-battery', 'AA Batteries', '🔋', 'length', 0.0505),
  u('hamster', 'Hamsters', '🐹', 'length', 0.15),
  u('house-cat', 'House Cats', '🐈', 'length', 0.46),
  u('labrador', 'Labradors', '🐕', 'length', 0.6),
  u('horse', 'Horses', '🐎', 'length', 2.4),
  u('ostrich', 'Ostriches', '🦤', 'length', 2.7),
  u('bald-eagle', 'Bald Eagles (wingspan)', '🦅', 'length', 2.3),
  u('wandering-albatross', 'Wandering Albatrosses (wingspan)', '🕊️', 'length', 3.4),
  u('american-football', 'American Footballs', '🏈', 'length', 0.28),
  u('baguette', 'Baguettes', '🥖', 'length', 0.6),
  u('chopstick', 'Chopsticks', '🥢', 'length', 0.23),
  u('red-solo-cup', 'Red Solo Cups', '🥤', 'length', 0.12, 'Height.'),
  u('oscar-statue', 'Oscar Statuettes', '🏆', 'length', 0.34),
  u('lego-brick', 'LEGO Bricks (2×4)', '🧱', 'length', 0.032),
  u('tennis-ball', 'Tennis Balls', '🎾', 'length', 0.067, 'Diameter.'),
  u('beach-ball', 'Beach Balls', '🏖️', 'length', 0.5, 'Diameter.'),
  u('pumpkin', 'Pumpkins', '🎃', 'length', 0.35),
  u('avocado', 'Avocados', '🥑', 'length', 0.12),
  u('chicken-nugget', 'Chicken Nuggets', '🍗', 'length', 0.02),
  u('french-fry', 'French Fries', '🍟', 'length', 0.07),
  u('taco', 'Tacos', '🌮', 'length', 0.15),
  u('sushi-roll', 'Sushi Rolls', '🍣', 'length', 0.05),
  u('ramen-brick', 'Instant Ramen Bricks', '🍜', 'length', 0.12),
  u('dollar-bill', 'US Dollar Bills', '💵', 'length', 0.156),
  u('vinyl-record', 'Vinyl Records', '💿', 'length', 0.305, 'Diameter.'),
  u('human-hair', 'Human Hairs', '💇', 'length', 0.0001, 'Typical strand thickness.'),
  u('ant', 'Ants', '🐜', 'length', 0.003),
  u('flea', 'Fleas', '🪲', 'length', 0.002),
  u('tardigrade', 'Tardigrades', '🦠', 'length', 0.0005),
  u('sperm-whale', 'Sperm Whales', '🐋', 'length', 16),
  u('megalodon', 'Megalodons', '🦷', 'length', 15, 'Estimated max.'),
  u('flamingo', 'Flamingos', '🦩', 'length', 1.2, 'Standing height.'),
  u('emperor-penguin', 'Emperor Penguins', '🐧', 'length', 1.15),
  u('sloth', 'Sloths', '🦥', 'length', 0.6),
  u('python', 'Burmese Pythons', '🐍', 'length', 5),
  u('komodo-dragon', 'Komodo Dragons', '🐉', 'length', 3),
  u('kangaroo', 'Kangaroos', '🦘', 'length', 1.6),
  u('moose', 'Moose', '🫎', 'length', 2.1, 'Shoulder height.'),
  u('walrus', 'Walruses', '🦭', 'length', 3.3),
  u('manatee', 'Manatees', '🧜', 'length', 3),
  u('dolphin', 'Bottlenose Dolphins', '🐬', 'length', 2.5),
  u('giant-octopus', 'Giant Pacific Octopuses (arm span)', '🐙', 'length', 9),
  u('lion-mane-jellyfish', 'Lion\'s Mane Jellyfish (tentacles)', '🪼', 'length', 36),
  u('redwood', 'Coast Redwoods', '🌲', 'length', 115, 'Typical mature height.'),
  u('sunflower', 'Sunflowers', '🌻', 'length', 3),
  u('telephone-pole', 'Telephone Poles', '📡', 'length', 12),
  u('lighthouse', 'Lighthouses', '🔦', 'length', 30, 'Average tower.'),
  u('wind-turbine-blade', 'Wind Turbine Blades', '💨', 'length', 80),
  u('saturn-v', 'Saturn V Rockets', '🚀', 'length', 110),
  u('space-shuttle', 'Space Shuttles', '🛸', 'length', 37),
  u('iss', 'International Space Stations', '🛰️', 'length', 109),
  u('moon', 'Moons (diameter)', '🌙', 'length', 3_474_000),
  u('light-year', 'Light-Years', '✨', 'length', 9.461e15),
  u('nfl-goalpost', 'NFL Goalposts', '🥅', 'length', 3.05, 'Crossbar height.'),
  u('golf-tee', 'Golf Tees', '⛳', 'length', 0.054),
  u('spaghetti-noodle', 'Spaghetti Noodles', '🍝', 'length', 0.25),
  u('pizza-slice', 'Pizza Slices', '🍕', 'length', 0.3),
  u('watermelon', 'Watermelons', '🍉', 'length', 0.35),
  u('playing-card', 'Playing Cards', '🃏', 'length', 0.089),
  u('cd', 'CDs', '💽', 'length', 0.12, 'Diameter.'),
  u('keyboard-key', 'Keyboard Keys', '⌨️', 'length', 0.019),
  u('rubber-duck', 'Rubber Ducks', '🦆', 'length', 0.08),
  u('rubiks-cube', 'Rubik\'s Cubes', '🧩', 'length', 0.057),
  u('traffic-cone', 'Traffic Cones', '🚧', 'length', 0.45),
  u('stop-sign', 'Stop Signs', '🛑', 'length', 0.76, 'Width.'),
  u('guitar', 'Acoustic Guitars', '🎸', 'length', 1.0),
  u('skateboard', 'Skateboards', '🛹', 'length', 0.81),
  u('surfboard', 'Surfboards', '🏄', 'length', 2.1),
  u('canoe', 'Canoes', '🛶', 'length', 4.5),
  u('christmas-tree', 'Christmas Trees', '🎄', 'length', 2.1, 'Living room standard.'),
  u('garden-gnome', 'Garden Gnomes', '🧙', 'length', 0.35),
  u('inflatable-flamingo', 'Inflatable Flamingos', '🦩', 'length', 1.5),

  // —— Mass (kilograms) ——
  u('capybara-mass', 'Capybaras (by weight)', '🦫', 'mass', 50),
  u('elephant', 'African Elephants', '🐘', 'mass', 6000),
  u('smartphone', 'Smartphones', '📱', 'mass', 0.2),
  u('hamburger', 'Double Cheeseburgers', '🍔', 'mass', 0.22),
  u('blue-whale-mass', 'Blue Whales (by weight)', '🐋', 'mass', 150000),
  u('house-cat-mass', 'House Cats (by weight)', '🐈', 'mass', 4.5),
  u('golden-retriever', 'Golden Retrievers', '🐕', 'mass', 32),
  u('polar-bear', 'Polar Bears', '🐻‍❄️', 'mass', 450),
  u('grizzly-bear', 'Grizzly Bears', '🐻', 'mass', 270),
  u('panda', 'Giant Pandas', '🐼', 'mass', 100),
  u('red-panda', 'Red Pandas', '🦊', 'mass', 5),
  u('koala', 'Koalas', '🐨', 'mass', 8),
  u('platypus', 'Platypuses', '🦫', 'mass', 1.5),
  u('hedgehog', 'Hedgehogs', '🦔', 'mass', 0.6),
  u('rabbit', 'Rabbits', '🐇', 'mass', 2),
  u('pig', 'Pigs', '🐷', 'mass', 100),
  u('cow', 'Cows', '🐄', 'mass', 700),
  u('horse-mass', 'Horses (by weight)', '🐎', 'mass', 500),
  u('donkey', 'Donkeys', '🫏', 'mass', 200),
  u('llama', 'Llamas', '🦙', 'mass', 150),
  u('alpaca', 'Alpacas', '🦙', 'mass', 70),
  u('goat', 'Goats', '🐐', 'mass', 50),
  u('sheep', 'Sheep', '🐑', 'mass', 70),
  u('chicken', 'Chickens', '🐔', 'mass', 2.5),
  u('turkey', 'Turkeys', '🦃', 'mass', 10),
  u('ostrich-mass', 'Ostriches (by weight)', '🦤', 'mass', 130),
  u('emu', 'Emus', '🦤', 'mass', 40),
  u('penguin-mass', 'Emperor Penguins (by weight)', '🐧', 'mass', 40),
  u('seal', 'Harbor Seals', '🦭', 'mass', 100),
  u('sea-lion', 'Sea Lions', '🦭', 'mass', 300),
  u('orca', 'Orcas', '🐋', 'mass', 6000),
  u('great-white-mass', 'Great White Sharks (by weight)', '🦈', 'mass', 1000),
  u('hammerhead', 'Hammerhead Sharks', '🦈', 'mass', 450),
  u('manta-ray', 'Manta Rays', '🐟', 'mass', 1200),
  u('lobster', 'Lobsters', '🦞', 'mass', 0.9),
  u('crab', 'King Crabs', '🦀', 'mass', 6),
  u('octopus-mass', 'Giant Pacific Octopuses (by weight)', '🐙', 'mass', 50),
  u('jellyfish-mass', 'Moon Jellyfish', '🪼', 'mass', 0.003),
  u('snail', 'Garden Snails', '🐌', 'mass', 0.01),
  u('frog', 'Bullfrogs', '🐸', 'mass', 0.35),
  u('turtle', 'Sea Turtles', '🐢', 'mass', 150),
  u('crocodile', 'Saltwater Crocodiles', '🐊', 'mass', 500),
  u('alligator', 'American Alligators', '🐊', 'mass', 360),
  u('t-rex-mass', 'T. Rexes (by weight)', '🦖', 'mass', 8000),
  u('triceratops', 'Triceratopses', '🦕', 'mass', 6000),
  u('stegosaurus', 'Stegosauruses', '🦕', 'mass', 3000),
  u('pterodactyl', 'Pterodactyls', '🦅', 'mass', 25),
  u('human', 'Average Adult Humans', '🧑', 'mass', 70),
  u('newborn-baby', 'Newborn Babies', '👶', 'mass', 3.5),
  u('sumo-wrestler', 'Sumo Wrestlers', '🤼', 'mass', 150),
  u('barbie', 'Barbie Dolls', '👱', 'mass', 0.11),
  u('action-figure', 'Action Figures', '🦸', 'mass', 0.15),
  u('bowling-ball', 'Bowling Balls', '🎳', 'mass', 7),
  u('dumbbell', '20 lb Dumbbells', '🏋️', 'mass', 9.07),
  u('piano-mass', 'Grand Pianos (by weight)', '🎹', 'mass', 270),
  u('car', 'Average Cars', '🚙', 'mass', 1500),
  u('tesla-mass', 'Tesla Model 3s (by weight)', '🚗', 'mass', 1840),
  u('school-bus-mass', 'School Buses (by weight)', '🚌', 'mass', 11340),
  u('locomotive', 'Locomotives', '🚂', 'mass', 120000),
  u('space-shuttle-mass', 'Space Shuttles (by weight)', '🛸', 'mass', 78000),
  u('statue-of-liberty-mass', 'Statues of Liberty (by weight)', '🗽', 'mass', 225000),
  u('eiffel-mass', 'Eiffel Towers (by weight)', '🗼', 'mass', 10100000),
  u('bag-of-rice', '5 lb Bags of Rice', '🍚', 'mass', 2.27),
  u('bag-of-flour', '5 lb Bags of Flour', '🌾', 'mass', 2.27),
  u('sugar-cube', 'Sugar Cubes', '🧊', 'mass', 0.003),
  u('salt-shake', 'Salt Shakers (full)', '🧂', 'mass', 0.15),
  u('pepper-grinder', 'Pepper Grinders (full)', '🌶️', 'mass', 0.4),
  u('avocado-mass', 'Avocados (by weight)', '🥑', 'mass', 0.2),
  u('apple', 'Apples', '🍎', 'mass', 0.18),
  u('watermelon-mass', 'Watermelons (by weight)', '🍉', 'mass', 5),
  u('pineapple', 'Pineapples', '🍍', 'mass', 1.5),
  u('coconut', 'Coconuts', '🥥', 'mass', 1.2),
  u('carrot', 'Carrots', '🥕', 'mass', 0.07),
  u('broccoli', 'Broccoli Crowns', '🥦', 'mass', 0.4),
  u('egg', 'Chicken Eggs', '🥚', 'mass', 0.06),
  u('dozen-eggs', 'Cartons of Eggs (dozen)', '🥚', 'mass', 0.68),
  u('stick-of-butter', 'Sticks of Butter', '🧈', 'mass', 0.113),
  u('loaf-of-bread', 'Loaves of Bread', '🍞', 'mass', 0.45),
  u('bagel', 'Bagels', '🥯', 'mass', 0.1),
  u('donut', 'Donuts', '🍩', 'mass', 0.06),
  u('croissant', 'Croissants', '🥐', 'mass', 0.05),
  u('pizza', 'Large Pizzas', '🍕', 'mass', 1.2),
  u('bucket-of-fried-chicken', 'Buckets of Fried Chicken', '🍗', 'mass', 1.5),
  u('soda-bottle-2l', '2L Soda Bottles (full)', '🥤', 'mass', 2.1),
  u('wine-bottle', 'Wine Bottles (full)', '🍷', 'mass', 1.2),
  u('keg-of-beer', 'Kegs of Beer', '🍺', 'mass', 72),
  u('gold-bar', 'Gold Bars (1 kg)', '🥇', 'mass', 1),
  u('brick', 'Bricks', '🧱', 'mass', 2.3),
  u('cinder-block', 'Cinder Blocks', '🧱', 'mass', 14),
  u('anvil', 'Anvils', '⚒️', 'mass', 100),
  u('sledgehammer', 'Sledgehammers', '🔨', 'mass', 5),
  u('microwave', 'Microwaves', '📻', 'mass', 15),
  u('toaster', 'Toasters', '🍞', 'mass', 2),
  u('laptop', 'Laptops', '💻', 'mass', 1.8),
  u('textbook', 'Textbooks', '📚', 'mass', 1.2),
  u('soccer-ball', 'Soccer Balls', '⚽', 'mass', 0.43),
  u('basketball', 'Basketballs', '🏀', 'mass', 0.62),
  u('baseball', 'Baseballs', '⚾', 'mass', 0.145),
  u('golf-ball-mass', 'Golf Balls', '⛳', 'mass', 0.046),
  u('tennis-ball-mass', 'Tennis Balls', '🎾', 'mass', 0.058),
  u('volleyball', 'Volleyballs', '🏐', 'mass', 0.27),
  u('frisbee', 'Frisbees', '🥏', 'mass', 0.175),
  u('yo-yo', 'Yo-Yos', '🪀', 'mass', 0.05),
  u('deck-of-cards', 'Decks of Cards', '🃏', 'mass', 0.1),
  u('roll-of-quarters', 'Rolls of Quarters', '🪙', 'mass', 0.227),

  // —— Volume (liters) ——
  u('olympic-pool', 'Olympic Swimming Pools', '🏊', 'volume', 2_500_000),
  u('bathtub', 'Bathtubs', '🛁', 'volume', 150),
  u('coffee-mug', 'Coffee Mugs', '☕', 'volume', 0.35),
  u('soda-can', 'Soda Cans', '🥤', 'volume', 0.355),
  u('teaspoon', 'Teaspoons', '🥄', 'volume', 0.00493),
  u('tablespoon', 'Tablespoons', '🥄', 'volume', 0.0148),
  u('shot-glass', 'Shot Glasses', '🥃', 'volume', 0.044),
  u('wine-glass', 'Wine Glasses', '🍷', 'volume', 0.15),
  u('water-bottle', 'Water Bottles', '💧', 'volume', 0.5),
  u('soda-bottle', '2L Soda Bottles', '🥤', 'volume', 2),
  u('milk-jug', 'Gallon Milk Jugs', '🥛', 'volume', 3.785),
  u('keg', 'Beer Kegs', '🍺', 'volume', 58.7),
  u('hot-tub', 'Hot Tubs', '♨️', 'volume', 1000),
  u('dumpster', 'Dumpsters', '🗑️', 'volume', 6000),
  u('swimming-pool-backyard', 'Backyard Pools', '🏊', 'volume', 45000),
  u('aquarium-home', 'Home Aquariums', '🐠', 'volume', 200),
  u('fish-bowl', 'Goldfish Bowls', '🐟', 'volume', 10),
  u('blender', 'Blenders (full)', '🫙', 'volume', 1.5),
  u('mixing-bowl', 'Mixing Bowls', '🥣', 'volume', 3),
  u('soup-can', 'Soup Cans', '🥫', 'volume', 0.4),
  u('paint-can', 'Gallon Paint Cans', '🎨', 'volume', 3.785),
  u('gas-tank-car', 'Car Gas Tanks', '⛽', 'volume', 50),
  u('tanker-truck', 'Tanker Trucks', '🚛', 'volume', 30000),
  u('rain-drop', 'Raindrops', '🌧️', 'volume', 0.00005),
  u('tear', 'Human Tears', '😢', 'volume', 0.0001),
  u('drop-of-blood', 'Drops of Blood', '🩸', 'volume', 0.00005),
  u('eyedropper', 'Eyedroppers', '💧', 'volume', 0.001),
  u('syringe', 'Syringes (10 mL)', '💉', 'volume', 0.01),
  u('iv-bag', 'IV Bags', '🏥', 'volume', 1),
  u('blood-donation', 'Blood Donation Bags', '🩸', 'volume', 0.5),
  u('honey-pot', 'Honey Pots', '🍯', 'volume', 0.5),
  u('jam-jar', 'Jam Jars', '🫙', 'volume', 0.37),
  u('pickle-jar', 'Pickle Jars', '🥒', 'volume', 1),
  u('peanut-butter-jar', 'Peanut Butter Jars', '🥜', 'volume', 0.5),
  u('ice-cream-tub', 'Tubs of Ice Cream', '🍦', 'volume', 1.5),
  u('cereal-box', 'Boxes of Cereal (volume)', '🥣', 'volume', 3),
  u('popcorn-bucket', 'Movie Popcorn Buckets', '🍿', 'volume', 2.5),
  u('bento-box', 'Bento Boxes', '🍱', 'volume', 0.8),
  u('lunchbox', 'Lunchboxes', '🍱', 'volume', 2),
  u('thermos', 'Thermoses', '🧴', 'volume', 0.75),
  u('flask', 'Hip Flasks', '🥃', 'volume', 0.2),
  u('perfume-bottle', 'Perfume Bottles', '💐', 'volume', 0.05),
  u('shampoo-bottle', 'Shampoo Bottles', '🧴', 'volume', 0.4),
  u('toothpaste-tube', 'Toothpaste Tubes', '🪥', 'volume', 0.1),
  u('soap-dispenser', 'Soap Dispensers (refill)', '🧼', 'volume', 0.5),
  u('bucket', 'Buckets', '🪣', 'volume', 10),
  u('wheelbarrow', 'Wheelbarrows (heaped)', '🛞', 'volume', 80),
  u('bathtub-boba', 'Bathtubs of Boba', '🧋', 'volume', 150),
  u('cloud', 'Cumulus Clouds', '☁️', 'volume', 1_000_000_000, 'Very approximate.'),
  u('hot-air-balloon', 'Hot Air Balloons', '🎈', 'volume', 2200),
  u('submarine-bathysphere', 'Bathyspheres', '🛟', 'volume', 2),
  u('suitcase-carryon', 'Carry-On Suitcases', '🧳', 'volume', 40),
  u('backpack-school', 'School Backpacks', '🎒', 'volume', 25),
  u('grocery-bag', 'Grocery Bags', '🛍️', 'volume', 20),
  u('trash-bag-kitchen', 'Kitchen Trash Bags', '🗑️', 'volume', 50),
  u('inflatable-pool', 'Inflatable Kiddie Pools', '🏖️', 'volume', 800),
  u('water-bed', 'Water Beds', '🛏️', 'volume', 800),
  u('fire-hydrant-flow', 'Fire Hydrant Flow (1 min)', '🚒', 'volume', 4000),
  u('fire-truck-tank', 'Fire Truck Tanks', '🚒', 'volume', 3000),
  u('swimming-pool-olympic-diving', 'Olympic Diving Wells', '🤿', 'volume', 500000),

  // —— Temperature (°C reference in toBase) ——
  u('room', 'Comfortable Rooms', '🏠', 'temperature', 21, 'Defined as 21 °C.'),
  u('surface-sun', 'Surfaces of the Sun', '☀️', 'temperature', 5500),
  u('lava', 'Fresh Lava', '🌋', 'temperature', 1200),
  u('freezer', 'Home Freezers', '🧊', 'temperature', -18),
  u('fridge', 'Refrigerators', '🥶', 'temperature', 4),
  u('human-body', 'Human Bodies', '🌡️', 'temperature', 37),
  u('hot-shower', 'Hot Showers', '🚿', 'temperature', 40),
  u('hot-coffee', 'Hot Coffee', '☕', 'temperature', 65),
  u('boiling-water', 'Boiling Water', '♨️', 'temperature', 100),
  u('baking-oven', 'Baking Ovens', '🍞', 'temperature', 180),
  u('pizza-oven', 'Pizza Ovens', '🍕', 'temperature', 400),
  u('campfire', 'Campfires', '🔥', 'temperature', 600),
  u('lightning-bolt', 'Lightning Bolts', '⚡', 'temperature', 30000, 'Plasma channel peak.'),
  u('antarctica-winter', 'Antarctic Winters', '🐧', 'temperature', -60),
  u('dry-ice', 'Dry Ice', '🧊', 'temperature', -78),
  u('liquid-nitrogen', 'Liquid Nitrogen', '🧪', 'temperature', -196),
  u('absolute-zero', 'Absolute Zero', '❄️', 'temperature', -273.15),
  u('surface-venus', 'Surfaces of Venus', '🪐', 'temperature', 465),
  u('surface-mars', 'Surfaces of Mars', '🔴', 'temperature', -63),
  u('core-earth', 'Earth\'s Outer Core', '🌍', 'temperature', 4000),
  u('welding-torch', 'Welding Torches', '🔧', 'temperature', 3000),
  u('candle-flame', 'Candle Flames', '🕯️', 'temperature', 1000),
  u('match-flame', 'Match Flames', '🔥', 'temperature', 600),
  u('sauna', 'Saunas', '🧖', 'temperature', 90),
  u('hot-spring', 'Hot Springs', '♨️', 'temperature', 70),
  u('death-valley-summer', 'Death Valley Summers', '🏜️', 'temperature', 54),
  u('siberia-winter', 'Siberian Winters', '🥶', 'temperature', -50),
  u('gpu-under-load', 'GPUs Under Load', '🖥️', 'temperature', 85),
  u('cpu-idle', 'CPUs at Idle', '💻', 'temperature', 45),
  u('spicy-ramen', 'Spicy Ramen', '🍜', 'temperature', 95),
]
